springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: false

server:
  port: 48193

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:user
    username: swagger
    password: qwerty
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true